[package]
name = "cal-jambonz"
version = "0.1.10"
edition = "2024"
description = "Jambonz Verbs"
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_repr = "0.1.20"
regex = "1.11.1"
ip-in-subnet = "0.1"
